### ISSUE TITLE
DD Agent 7.42.1 breaks hostname resolution when run in K8S

### ISSUE THREAD

**Issue by greenaar** [redis-field-engineering/Docker-Datadog-Redis-Cloud#3]
2023-03-29 16:24:35 UTC | CORE | INFO | (cmd/agent/subcommands/run/command.go:241 in startAgent) | Starting Datadog Agent v7.42.1
2023-03-29 16:24:35 UTC | CORE | INFO | (cmd/agent/subcommands/run/command.go:292 in startAgent) | pid '736' written to pid file '/opt/datadog-agent/run/agent.pid'
2023-03-29 16:24:35 UTC | CORE | ERROR | (cmd/agent/subcommands/run/command.go:302 in startAgent) | Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file

https://github.com/DataDog/datadog-agent/issues/14152

**Comment by greenaar** [comment]
Ok, i've identified the issue.

We are setting DD_HOSTNAME_TRUST_UTS_NAMESPACE as an environment variable, but the container is doing

exec su - dd-agent -c "/opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid"

When it should be doing 

exec su -p dd-agent -c "/opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid"

To preserve incoming environment variables, otherwise they're lost.

**Comment by jdb-apollo** [comment]
Are you aware of any workaround for this issue?

**Comment by greenaar** [comment]
I forked the repo, and rebuilt with the change mentioned above, and everything worked. 

The docker container should either run as the dd-agent on start, or preserve environment variables as it passes through to that user.  Either of those would allow the full range of DD variables to be set, otherwise you're limited to a very small handful which doesn't include the one needed to run this in K8S.

**Comment by banker** [comment]
Thanks for investigating this, @greenaar. Can you confirm that the attached PR fixes the issue?

**Comment by rajesh-dhakad** [comment]
I can confirm this works for me with fix and an additional flag ( `-e DD_HOSTNAME_TRUST_UTS_NAMESPACE=true` )
`exec su -p dd-agent -c "/opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid"`

**Comment by banker** [comment]
Thanks, @rajesh-dhakad. See the attached PR for the included fix.
